services:
  mysql:
    container_name: mysql
    image: mysql:8.4
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    healthcheck:
        test: ["CMD-SHELL", "mysqladmin ping -h localhost -u test"]
        interval: 5s
        timeout: 5s
        retries: 5

  redis:
    container_name: redis
    image: redis:7.4
    ports:
      - "6379:6379"
    command: redis-server --requirepass test
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 5s
      timeout: 5s
      retries: 5
