FROM node:20
WORKDIR /opt/app

COPY ["package.json", "yarn.lock", "./"]
RUN ["yarn", "install", "--frozen-lockfile", "--non-interactive"]

COPY ["./tsconfig.json", "./tsconfig.build.json", "./"]
COPY ["./nest-cli.json", "./"]
COPY [".eslintrc.js", ".prettierrc", "./"]
COPY ["./src", "./"]
COPY ["./test", "./"]

ENTRYPOINT ["yarn", "start"]