export enum ExceptionCode {
  NOT_FOUND = 'NOT_FOUND',
  ILLEGAL_ARGUMENT = 'ILLEGAL_ARGUMENT',
  ILLEGAL_STATE = 'ILLEGAL_STATE',
  ALREADY_EXIST = 'ALREADY_EXIST',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
