export const ACTIVITY_REPOSITORY = 'ACTIVITY_REPOSITORY';
export const ACTIVITY_LOCATION_REPOSITORY = 'ACTIVITY_LOCATION_REPOSITORY';
export const PARTICIPATION_REPOSITORY = 'PARTICIPATION_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const TOKEN_REPOSITORY = 'TOKEN_REPOSITORY';
export const GENERATION_REPOSITORY = 'GENERATION_REPOSITORY';

export const REDIS_CLIENT = 'REDIS_CLIENT';
export const TIME = 'TIME';
export const WINSTON_LOGGER = 'WINSTON_LOGGER';
