name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: "Install dependencies"
      - run: yarn install --frozen-lockfile

      - name: "Building"
      - run: yarn build

#       - name: "Testing"
#       - run: yarn test
