export const ACTIVITY_REPOSITORY = 'ACTIVITY_REPOSITORY';
export const REFRESH_TOKEN_REPOSITORY = 'TOKEN_REPOSITORY';
export const REDIS_CLIENT = 'REDIS_CLIENT';

export enum ENVIRONMENT {
  DEVELOPMENT = 'development',
  PRODUCTION = 'production',
}
