### 선생님으로 등록
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "name": "{{name}}",
  "email": "{{email}}",
  "memberType": "선생님",
  "password": "{{password}}"
}

### 학생으로 등록
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{
  "name": "{{name}}",
  "email": "{{school_email}}",
  "memberType": "학생",
  "password": "{{password}}",
  "generationNumber": 7
}