name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push App
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/app:latest,${{ secrets.DOCKERHUB_USERNAME }}/app:${{ github.sha }}
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/app:cache
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/app:cache,mode=max

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
        run: |
          mkdir -p ~/.ssh
          eval $(ssh-agent -s)
          echo "$SSH_PRIVATE_KEY" | ssh-add -
          echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

      - name: Create Docker Context
        env:
          USERNAME: ${{ secrets.USERNAME }}
          HOST: ${{ secrets.HOST }}
        run: |
          docker context create aftermeal --docker "host=ssh://$USERNAME@$HOST"
          docker context use aftermeal

      - name: Deploy application
        env:
            NODE_ENV: ${{ secrets.NODE_ENV }}
            APP_PORT: ${{ secrets.APP_PORT }}
            BASE_URL: ${{ secrets.BASE_URL }}
            DB_HOST: ${{ secrets.DB_HOST }}
            DB_PORT: ${{ secrets.DB_PORT }}
            DB_USER: ${{ secrets.DB_USER }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            DB_NAME: ${{ secrets.DB_NAME }}
            DB_LOGGING: ${{ secrets.DB_LOGGING }}
            ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
            ACCESS_TOKEN_EXPIRATION_TIME: ${{ secrets.ACCESS_TOKEN_EXPIRATION_TIME }}
            REFRESH_TOKEN_EXPIRATION_TIME: ${{ secrets.REFRESH_TOKEN_EXPIRATION_TIME }}
            EMAIL_VERIFICATION_TOKEN_EXPIRATION_TIME: ${{ secrets.EMAIL_VERIFICATION_TOKEN_EXPIRATION_TIME }}
            REDIS_HOST: ${{ secrets.REDIS_HOST }}
            REDIS_PORT: ${{ secrets.REDIS_PORT }}
            REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
            EMAIL_SERVICE: ${{ secrets.EMAIL_SERVICE }}
            EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
            EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
            EMAIL_AUTH_USER: ${{ secrets.EMAIL_AUTH_USER }}
            EMAIL_AUTH_PASSWORD: ${{ secrets.EMAIL_AUTH_PASSWORD }}
        run: |
          docker compose pull app

          if docker ps -q -f name=app | grep -q .; then
            docker stop app
            docker rm app
          fi

          docker compose up -d --no-deps app

      - name: Clean up
        run: |
          docker image prune -f
